#
# Make latex using tex4ht
#

HTFONTS=/usr/share/texmf/tex/generic/tex4ht/ht-fonts/
TEXEXTS=.4ct .aux .dvi .xref .4tc .idx .log .tmp .lg .idv

# The contents list for the sidebar is not wanted in the chm help files.
ifneq ($(HTMLFMT),chm)
POSTPROCOPTS=-s
endif
	
$(HTMLDIR)/%.chk: %.tex
	rm -rf $(basename $@)
	rm -f $(addprefix $(basename $<),$(TEXEXTS))
	cp -f tex/preamble.ts4 tex/preamble.inc
ifneq ($(HTMLFMT),chm)
	cat tex/preamble.switch >> tex/preamble.inc
endif
	$(GINSTALL) -d $(basename $@) -m755
	$(LATEX) -output-directory=$(HTMLDIR)/$(basename $(notdir $<)) $<
	$(LATEX) -output-directory=$(HTMLDIR)/$(basename $(notdir $<)) $<
	$(LATEX) -output-directory=$(HTMLDIR)/$(basename $(notdir $<)) $<
ifdef inUnix	
#	for ext in $(TEXEXTS); do [ -f $(basename $<)$$ext ] && mv $(basename $<)$$ext $(basename $<); done || true
	cp -f -r ./pics/ $(basename $@)/pics/
else
#	mkdir $(basename $<)
#	for /D %%i in ($(TEXEXTS)) do if exist $(basename $<)%%i xcopy $(basename $<)%%i $(basename $<) 
	cp -f -r ./pics $(basename $@)/pics
endif
	cd $(basename $@) && tex4ht $(basename $(notdir $<))  && t4ht $(basename $(notdir $<)) -m644
#	rm -f -r $(basename $@)/pics
	cp -f css/*.css $(basename $@)/
ifneq ($(HTMLFMT),chm)
	cp -f css/*.js $(basename $@)/
endif
	rm -f $(addprefix $(basename $@)/$(basename $(notdir $<)),$(TEXEXTS))
	./postproc$(EXEEXT) -v -t $(POSTPROCOPTS) -b $(HTMLDIR)/ -d $(HTMLDIR)/$(basename $(notdir $<))
	touch $@
