#
# Create HTML using hevea tex 2 html conversion
#

%.chk: %.tex fpc-hevea.tex
	cp -f preamble.hevea preamble.inc
	$(HEVEA) $(HEVEAOPTS) $<
	touch $(basename $<).chk
	mkdir $(basename $<)
	mv -f $(basename $<).html $(basename $<)/$(basename $<).html

user.chk: $(INCLUDES) user.tex messages.inc
prog.chk: $(INCLUDES) prog.tex
onechap.chk: $(INCLUDES) onechap.tex
ref.chk: $(INCLUDES) ref.tex
rtl.chk: $(INCLUDES) rtl.tex
fpdoc.chk: $(INCLUDES) fpdoc.tex

